[files]
extend-exclude = [
	".cache",
	"node_modules",
	"examples/append-sequences/append-sequences",
	"examples/basic-merge/basic-merge",
	"examples/clone-merge/clone-merge",
	"examples/find-update/find-update",
]

[default.extend-words]
go-yaml = "go-yaml"
go-yaml-dom = "go-yaml-dom"
go-yaml-yq = "go-yaml-yq"
